
HUBS = [
    "Desert and Pacific Hub",
    "Great Lakes Hub",
    "Great Plains Hub",
    "Interior Northeast Hub",
    "Mid-Atlantic Hub",
    "Mid-South Hub",
    "New England Hub",
    "New York Hub",
    "Northeast Hub",
    "Northwest Hub",
    "Southeast Hub",
    "Southwest Hub",
    "West Hub"
]


UNIVERSITIES = [
    ("Arizona State University", "Desert and Pacific Hub"),
    ("Boise State University", "Desert and Pacific Hub"),
    ("Northern Arizona University", "Desert and Pacific Hub"),
    ("San Diego State University", "Desert and Pacific Hub"),
    ("The University of Arizona", "Desert and Pacific Hub"),
    ("University of California, San Diego", "Desert and Pacific Hub"),
    ("University of Hawaiʻi at Mānoa", "Desert and Pacific Hub"),
    ("University of Idaho", "Desert and Pacific Hub"),
    ("The University of Nevada, Las Vegas", "Desert and Pacific Hub"),
    ("The University of Michigan", "Great Lakes Hub"),
    ("Iowa State University", "Great Lakes Hub"),
    ("Michigan Technological University", "Great Lakes Hub"),
    ("Missouri University of Science and Technology", "Great Lakes Hub"),
    ("Purdue University", "Great Lakes Hub"),
    ("The University of Akron", "Great Lakes Hub"),
    ("The University of Chicago", "Great Lakes Hub"),
    ("University of Illinois Urbana–Champaign", "Great Lakes Hub"),
    ("The University of Iowa", "Great Lakes Hub"),
    ("The University of Minnesota", "Great Lakes Hub"),
    ("The University of Nebraska–Lincoln", "Great Lakes Hub"),
    ("The University of Toledo", "Great Lakes Hub"),
    ("The University of Wisconsin–Madison", "Great Lakes Hub"),
    ("The University of Wisconsin–Milwaukee", "Great Lakes Hub"),
    ("North Dakota State University", "Great Plains Hub"),
    ("Dakota State University", "Great Plains Hub"),
    ("South Dakota School of Mines and Technology", "Great Plains Hub"),
    ("South Dakota State University", "Great Plains Hub"),
    ("The University of Montana", "Great Plains Hub"),
    ("The University of Nebraska at Omaha", "Great Plains Hub"),
    ("The University of North Dakota", "Great Plains Hub"),
    ("The University of South Dakota", "Great Plains Hub"),
    ("University of Wyoming", "Great Plains Hub"),
    ("Wichita State University", "Great Plains Hub"),
    ("Cornell University", "Interior Northeast Hub"),
    ("Binghamton University, State University of New York", "Interior Northeast Hub"),
    ("Dartmouth College", "Interior Northeast Hub"),
    ("Rochester Institute of Technology", "Interior Northeast Hub"),
    ("Syracuse University", "Interior Northeast Hub"),
    ("University at Buffalo, State University of New York", "Interior Northeast Hub"),
    ("The University of Pittsburgh", "Interior Northeast Hub"),
    ("The University of Rochester", "Interior Northeast Hub"),
    ("The University of Vermont", "Interior Northeast Hub"),
    ("West Virginia University", "Interior Northeast Hub"),
    ("The University of Maryland, College Park", "Mid-Atlantic Hub"),
    ("Carnegie Mellon University", "Mid-Atlantic Hub"),
    ("The George Washington University", "Mid-Atlantic Hub"),
    ("Hampton University", "Mid-Atlantic Hub"),
    ("Howard University", "Mid-Atlantic Hub"),
    ("Johns Hopkins University", "Mid-Atlantic Hub"),
    ("North Carolina State University", "Mid-Atlantic Hub"),
    ("The Pennsylvania State University", "Mid-Atlantic Hub"),
    ("The University of North Carolina at Chapel Hill", "Mid-Atlantic Hub"),
    ("The University of North Carolina at Charlotte", "Mid-Atlantic Hub"),
    ("University of Pennsylvania", "Mid-Atlantic Hub"),
    ("Virginia Polytechnic Institute and State University", "Mid-Atlantic Hub"),
    ("Vanderbilt University", "Mid-South Hub"),
    ("George Mason University", "Mid-South Hub"),
    ("Jackson State University", "Mid-South Hub"),
    ("Meharry Medical College", "Mid-South Hub"),
    ("Tennessee State University", "Mid-South Hub"),
    ("University of Arkansas", "Mid-South Hub"),
    ("The University of Kentucky", "Mid-South Hub"),
    ("The University of Louisville", "Mid-South Hub"),
    ("The University of Memphis", "Mid-South Hub"),
    ("The University of Tennessee, Knoxville", "Mid-South Hub"),
    ("The University of Virginia", "Mid-South Hub"),
    ("Massachusetts Institute of Technology", "New England Hub"),
    ("Brown University", "New England Hub"),
    ("Harvard University", "New England Hub"),
    ("Northeastern University", "New England Hub"),
    ("Tufts University", "New England Hub"),
    ("The University of Maine", "New England Hub"),
    ("University of Massachusetts Amherst", "New England Hub"),
    ("University of New Hampshire", "New England Hub"),
    ("The City University of New York", "New York Hub"),
    ("Clarkson University", "New York Hub"),
    ("Columbia University", "New York Hub"),
    ("Icahn School of Medicine at Mount Sinai", "New York Hub"),
    ("New York University", "New York Hub"),
    ("Rensselaer Polytechnic Institute", "New York Hub"),
    ("Rockefeller University", "New York Hub"),
    ("Stevens Institute of Technology", "New York Hub"),
    ("Stony Brook University, State University of New York", "New York Hub"),
    ("University at Albany, State University of New York", "New York Hub"),
    ("University of Massachusetts Medical School", "New York Hub"),
    ("Princeton University", "Northeast Hub"),
    ("Delaware State University", "Northeast Hub"),
    ("Drexel University", "Northeast Hub"),
    ("Lehigh University", "Northeast Hub"),
    ("New Jersey Institute of Technology", "Northeast Hub"),
    ("Rutgers, The State University of New Jersey", "Northeast Hub"),
    ("Rowan University", "Northeast Hub"),
    ("Temple University", "Northeast Hub"),
    ("The University of Connecticut", "Northeast Hub"),
    ("The University of Delaware", "Northeast Hub"),
    ("Yale University", "Northeast Hub"),
    ("University of California, Berkeley", "Northwest Hub"),
    ("Oregon State University", "Northwest Hub"),
    ("University of Alaska Fairbanks", "Northwest Hub"),
    ("University of California, Davis", "Northwest Hub"),
    ("University of California, Irvine", "Northwest Hub"),
    ("University of California, San Francisco", "Northwest Hub"),
    ("University of California, Santa Cruz", "Northwest Hub"),
    ("The University of Washington", "Northwest Hub"),
    ("Georgia Institute of Technology", "Southeast Hub"),
    ("Clemson University", "Southeast Hub"),
    ("Morehouse College", "Southeast Hub"),
    ("The University of Alabama", "Southeast Hub"),
    ("University of Central Florida", "Southeast Hub"),
    ("The University of Florida", "Southeast Hub"),
    ("University of Miami", "Southeast Hub"),
    ("University of South Florida", "Southeast Hub"),
    ("The University of Texas at Austin", "Southwest Hub"),
    ("Louisiana State University", "Southwest Hub"),
    ("Mississippi State University", "Southwest Hub"),
    ("New Mexico State University", "Southwest Hub"),
    ("Oklahoma State University", "Southwest Hub"),
    ("Rice University", "Southwest Hub"),
    ("Texas A&M University", "Southwest Hub"),
    ("The University of Texas at El Paso", "Southwest Hub"),
    ("The University of Texas at San Antonio", "Southwest Hub"),
    ("University of Southern California", "West Hub"),
    ("California Institute of Technology", "West Hub"),
    ("Colorado School of Mines", "West Hub"),
    ("Colorado State University", "West Hub"),
    ("University of California, Los Angeles", "West Hub"),
    ("University of California, Riverside", "West Hub"),
    ("University of California, Santa Barbara", "West Hub"),
    ("University of Colorado Boulder", "West Hub"),
    ("Texas Tech University", "West Hub"),
    ("The University of New Mexico", "West Hub"),
    ("The University of Utah", "West Hub")
]
